In [1]:
from vibegrad import Tensor

In [2]:
a = Tensor(2)
b = Tensor(4)

In [3]:
c = a*b
c.backward()
c.grad

1

In [4]:
b.grad, a.grad

(2.0, 4.0)

In [5]:
c.zero_grad()
a.zero_grad()
b.zero_grad()

In [6]:
from vibegrad.nn import Linear, Sequential

In [7]:
a = Linear(1, 1)

In [8]:
import numpy as np
np.random.uniform((1,1))

array([1., 1.])

In [9]:
a(Tensor([1,1]))

TypeError: unsupported operand type(s) for @: 'Tensor' and 'Tensor'

In [10]:
a.weight, a.bias

(Tensor(data=[[0.68452231]]), array([0.]))

In [11]:
import torch
from torch.nn import Linear as tLinear

In [12]:
a = tLinear(1,1)

In [13]:
a(torch.tensor([1.0]))

tensor([-1.2912], grad_fn=<ViewBackward0>)

In [14]:
a.weight, a.bias

(Parameter containing:
 tensor([[-0.4282]], requires_grad=True),
 Parameter containing:
 tensor([-0.8630], requires_grad=True))

In [15]:
from vibegrad.nn import *

In [16]:
model = Sequential([
    Linear(256, 300),
    ReLU(),
    Linear(300, 300),
    ReLU(),
    Linear(300, 10)
])
model

In [17]:
model.parameters

'Linear(256, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x7fbc2022ffa0>Linear(300, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x7fbc202e2290>Linear(300, 10, bias=True) '

In [18]:
model.total_params()

170410

In [19]:
X = np.random.uniform(size=(100, 256))
y = np.random.uniform(size=(10, 100))
X = Tensor(X)
y = Tensor(y)
X

Tensor(data=[[0.27959942 0.26186485 0.52413634 ... 0.31278202 0.36209844 0.51958713]
 [0.66481412 0.52562672 0.2046829  ... 0.98365679 0.9927941  0.09442994]
 [0.46308152 0.89573071 0.34120522 ... 0.34779458 0.41016819 0.08077314]
 ...
 [0.23854799 0.74176259 0.17512489 ... 0.46465989 0.46752906 0.50729411]
 [0.29819697 0.00108592 0.63744529 ... 0.21057172 0.35209872 0.84460969]
 [0.27958101 0.08618357 0.81267327 ... 0.97538469 0.1078671  0.84494009]])

In [20]:
model(X)

TypeError: unsupported operand type(s) for @: 'Tensor' and 'Tensor'

In [ ]:
model = torch.nn.Sequential()
model.append(torch.nn.Linear(256, 300))
model.append(torch.nn.Linear(300,300))
model.append(torch.nn.Linear(300,10))

In [ ]:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of parameters: {total_params}")

In [ ]:
model.parameters

In [ ]:
import vibegrad.nn as nn

In [ ]:
nn.relu(Tensor(2.0))