In [1]:
from vibegrad import Tensor

In [2]:
a = Tensor(2)
b = Tensor(4)

In [3]:
c = a*b
c.backward()
c.grad

1

In [4]:
b.grad, a.grad

(2.0, 4.0)

In [5]:
c.zero_grad()
a.zero_grad()
b.zero_grad()

In [6]:
from vibegrad.nn import Linear, Sequential

In [7]:
a = Linear(1, 1)

In [8]:
import numpy as np
np.random.uniform((1,1))

array([1., 1.])

In [9]:
a(Tensor([1]))

Tensor(data=[0.36063824])

In [10]:
a.weight, a.bias

(Tensor(data=[[0.36063824]]), array([0.]))

In [11]:
import torch
from torch.nn import Linear as tLinear

In [12]:
a = tLinear(1,1)

In [13]:
a(torch.tensor([1.0]))

tensor([-1.0912], grad_fn=<ViewBackward0>)

In [14]:
a.weight, a.bias

(Parameter containing:
 tensor([[-0.8610]], requires_grad=True),
 Parameter containing:
 tensor([-0.2302], requires_grad=True))

In [15]:
from vibegrad.nn import *

In [16]:
model = Sequential([
    Linear(256, 300),
    ReLU(),
    Linear(300, 300),
    ReLU(),
    Linear(300, 10),
    Sigmoid()
])
model

In [17]:
model.parameters

'Linear(256, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x78230ce2a1d0>Linear(300, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x78230ce2ad40>Linear(300, 10, bias=True) <vibegrad.nn.activations.Sigmoid object at 0x78230ce2a200>'

In [18]:
model.total_params()

170410

In [19]:
X = np.random.uniform(-1, 1, size=(100, 256))
y = np.random.choice([0, 1], size=(100, 10), p=[0.5, 0.5])
X.shape
X = Tensor(X)
y = Tensor(y) 
y.data[:5]

array([[0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 1, 0, 0]])

In [20]:
out = model(X)
out.data.shape, y.data.shape

((100, 10), (100, 10))

In [21]:
loss_fn = BCELoss(reduction="mean")
print(out)
loss = loss_fn(out, y)
print(loss)

Tensor(data=[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         0.99999999 1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [0.50478    0.5045781  0.50492245 0.50493403 0.50484436 0.50486404
  0.50459781 0.50493749 0.50469422 0.50491557]
 [0.99998415 0.99998482 0.9999899  0.99998887 0.99998618 0.99998754
  0.99997963 0.99998759 0.99997617 0.99998792]
 [0.51275556 0.51289545 0.51317659 0.51318522 0.51302364 0.51327754
  0.51273618 0.51324202 0.51233495 0.51328406]
 [0.90374019 0.90433488 0.91115241 0.9096726  0.90567458 0.90785542
  0.90005659 0.90777582 0.89531833 0.90756914]
 [0.99985578 0.9998579  0.99989664 0.99988839 0.99986845 0.99988163
  0.99982682 0.9998809  0.999792

In [22]:
import torch
out = torch.tensor(out.data)
y = torch.tensor(y.data)
loss_fn_torch = torch.nn.BCELoss()
y = y.float()
out = out.float()
loss_fn_torch(out, y)

tensor(15.1299)

In [23]:
a = Tensor([[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0]])

for ding in a.data:
    for dong in ding:
        if dong != 1 and dong != 0:
            raise ValueError("ding dong")    

In [24]:
prediction = Tensor(np.array([0.9, 0.4, 0.7, 0.2]))
target = Tensor(np.array([1, 0, 1, 0]))

loss_fn = BCELoss()
loss = loss_fn(prediction, target)
print(loss)
loss.backward()

0.2990011586691898


AttributeError: 'numpy.float64' object has no attribute 'backward'

In [23]:
model = torch.nn.Sequential()
model.append(torch.nn.Linear(256, 300))
model.append(torch.nn.Linear(300,300))
model.append(torch.nn.Linear(300,10))

Sequential(
  (0): Linear(in_features=256, out_features=300, bias=True)
  (1): Linear(in_features=300, out_features=300, bias=True)
  (2): Linear(in_features=300, out_features=10, bias=True)
)

In [24]:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of parameters: {total_params}")

Total number of parameters: 170410


In [25]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=256, out_features=300, bias=True)
  (1): Linear(in_features=300, out_features=300, bias=True)
  (2): Linear(in_features=300, out_features=10, bias=True)
)>

In [26]:
import vibegrad.nn as nn

In [27]:
nn.relu(Tensor(2.0))

Tensor(data=2.0)