In [1]:
from vibegrad import Tensor

In [2]:
a = Tensor(2)
b = Tensor(4)

In [3]:
c = a*b
c.backward()
c.grad

1

In [4]:
b.grad, a.grad

(2.0, 4.0)

In [5]:
c.zero_grad()
a.zero_grad()
b.zero_grad()

In [6]:
from vibegrad.nn import Linear, Sequential

In [7]:
a = Linear(1, 1)

In [8]:
import numpy as np
np.random.uniform((1,1))

array([1., 1.])

In [9]:
a(Tensor([1]))

Tensor(data=[0.08782648])

In [10]:
a.weight, a.bias

(Tensor(data=[[0.08782648]]), array([0.]))

In [11]:
import torch
from torch.nn import Linear as tLinear

In [12]:
a = tLinear(1,1)

In [13]:
a(torch.tensor([1.0]))

tensor([-0.4297], grad_fn=<ViewBackward0>)

In [14]:
a.weight, a.bias

(Parameter containing:
 tensor([[0.2292]], requires_grad=True),
 Parameter containing:
 tensor([-0.6589], requires_grad=True))

In [15]:
from vibegrad.nn import *

In [16]:
model = Sequential([
    Linear(256, 300),
    ReLU(),
    Linear(300, 300),
    ReLU(),
    Linear(300, 10)
])
model

In [17]:
model.parameters

'Linear(256, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x796e6bf363e0>Linear(300, 300, bias=True) <vibegrad.nn.activations.ReLU object at 0x796e6bf36350>Linear(300, 10, bias=True) '

In [18]:
model.total_params()

170410

In [19]:
X = np.random.uniform(size=(100, 256))
y = np.random.uniform(size=(10, 100))
X = Tensor(X)
y = Tensor(y)
X

Tensor(data=[[0.56117889 0.46101924 0.03563299 ... 0.26657794 0.92739686 0.40899876]
 [0.44304007 0.12940983 0.00644432 ... 0.33842634 0.61760703 0.7715335 ]
 [0.98311093 0.12239235 0.46804165 ... 0.26101726 0.11192801 0.18248924]
 ...
 [0.00966137 0.4324736  0.17288334 ... 0.85846316 0.06273254 0.1443506 ]
 [0.35667368 0.08525806 0.38755749 ... 0.63791108 0.1321052  0.60635366]
 [0.9419585  0.06724693 0.93471899 ... 0.34290962 0.19648993 0.30148619]])

In [20]:
model(X)

Tensor(data=[[294.56781951 291.52078187 288.75122281 301.43939641 308.18117877
  295.56596129 284.52941014 306.40436077 285.23530125 319.32025181]
 [288.90363286 285.93788372 283.20107644 295.6444634  302.25819818
  289.89250183 279.064972   300.52078749 279.76041329 313.1921826 ]
 [306.74676405 303.58160374 300.69134497 313.91276383 320.92404719
  307.78805553 296.30002516 319.0827025  297.02523769 332.53229188]
 [290.84675609 287.84948708 285.09928119 297.62956338 304.28689286
  291.83689493 280.9279592  302.53595848 281.63657349 315.28450744]
 [302.29882989 299.18277958 296.32463384 309.35987597 316.26090357
  303.32071123 292.00068983 314.44679759 292.71344296 327.70818588]
 [288.79730322 285.80342993 283.08998067 295.53641693 302.12959458
  289.76483592 278.95658373 300.37718686 279.63816518 313.07035569]
 [295.27032878 292.226952   289.43495161 302.16045238 308.91342828
  296.26944104 285.2040061  307.1282133  285.89902156 320.08500387]
 [299.65840716 296.57127598 293.72813838 30

In [21]:
model = torch.nn.Sequential()
model.append(torch.nn.Linear(256, 300))
model.append(torch.nn.Linear(300,300))
model.append(torch.nn.Linear(300,10))

Sequential(
  (0): Linear(in_features=256, out_features=300, bias=True)
  (1): Linear(in_features=300, out_features=300, bias=True)
  (2): Linear(in_features=300, out_features=10, bias=True)
)

In [22]:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of parameters: {total_params}")

Total number of parameters: 170410


In [23]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=256, out_features=300, bias=True)
  (1): Linear(in_features=300, out_features=300, bias=True)
  (2): Linear(in_features=300, out_features=10, bias=True)
)>

In [24]:
import vibegrad.nn as nn

In [25]:
nn.relu(Tensor(2.0))

Tensor(data=2.0)